version: "3.7"

services:
  better-banking:
    image: better-banking:v1.0.0
    restart: on-failure
    ports:
      - 8081:8081
    networks:
      - myNet
    environment:
      EXTERNAL_BANKING_API_URL: host.docker.internal:8080
      SPRING_REDIS_HOST: redis
    depends_on:
      - redis

  redis:
    image: redis:6.2.1-alpine
    restart: on-failure
    ports:
      - 6379:6379
    networks:
      - myNet

networks:
  myNet:
